<?php
// module/User/view/user/user/add.phtml:

$title = 'Add new user';
$this->headUsername($username);
?>
<h1><?php echo $this->escapeHtml($username); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

//Alternate form display
//echo $this->formCollection($form);