<?php
// module/Project/view/project/project/add.phtml:

$title = 'Add new project';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('project', array('action' => 'add')));
$form->prepare();

/*echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('game'));
echo $this->formRow($form->get('count'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();*/

//Alternate form display
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();