<?php
// module/Project/view/project/project/delete.phtml:

$title = 'Delete project';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete your project?
    <!-- '<?php echo $this->escapeHtml($project->game); ?>' by
    '<?php echo $this->escapeHtml($project->count); ?>'? -->
</p>
<?php
$url = $this->url('project', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $project->id; ?>" />
    <input type="submit" name="del" value="Yes" class="btn btn-success"/>
    <input type="submit" name="del" value="No" class="btn btn-success"/>
</div>
</form>