<?php
// module/Project/view/project/project/index.phtml:

$title = 'My projects';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('project', array('action'=>'add'));?>">Add new project</a>
</p>

<table class="table">
<tr>
    <th>Game</th>
    <th>Count</th>
    <th>Budget</th>
    <th>Detail Level</th>
    <th>Last Modified</th>
    <th>Created</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($projects as $project) : ?>
<tr>
    <td><?php echo $this->escapeHtml($project->game);?></td>
    <td><?php echo $this->escapeHtml($project->count);?></td>
    <td><?php echo $this->escapeHtml($project->budget);?></td>
    <td><?php echo $this->escapeHtml($project->detail_level);?></td>
    <td><?php echo $this->escapeHtml($project->date_modified);?></td>
    <td><?php echo $this->escapeHtml($project->date_created);?></td>
    <td>
        <a href="<?php echo $this->url('project',
            array('action'=>'view', 'id' => $project->id));?>">View</a>
        <a href="<?php echo $this->url('project',
            array('action'=>'edit', 'id' => $project->id));?>">Edit</a>
        <a href="<?php echo $this->url('project',
            array('action'=>'delete', 'id' => $project->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>