<?php
// module/Profile/view/profile/profile/index.phtml:

$title = 'My profiles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('profile', array('action'=>'add'));?>">Add new profile</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($profiles as $profile) : ?>
<tr>
    <td><?php echo $this->escapeHtml($profile->title);?></td>
    <td><?php echo $this->escapeHtml($profile->artist);?></td>
    <td>
        <a href="<?php echo $this->url('profile',
            array('action'=>'edit', 'id' => $profile->id));?>"><span class="edit"></span></a>
        <a href="<?php echo $this->url('profile',
            array('action'=>'delete', 'id' => $profile->id));?>"><span class="delete"></span></a>
    </td>
</tr>
<?php endforeach; ?>
</table>