<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Freelancemins')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <div class="container">
                <div style="float:right; color:#ffffff; padding-right:10px;padding-top:20px;">
                    <span class="user"></span>
                    <?php
                     if($this->zfcUserIdentity()){
                        echo '<a href="/user">';
                        echo $this->zfcUserDisplayName();
                        echo '</a>';
                     }else{
                         echo '<a href="/user/login">sign in</a>';
                     }
                ?>
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp; Freelance Minis</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li class="active"><a href="<?php echo $this->url('about') ?>">About Us</a></li>
                        <?php if($this->zfcUserIdentity()){ ?>
                            <?php if($this->zfcUserIdentity()->getRoleID() != 2){ ?>
                                <li class="active"><a href="<?php echo $this->url('proposal') ?>"><?php echo $this->translate('Proposals') ?></a></li>
                            <?php }?>
                            <li class="active"><a href="<?php echo $this->url('project') ?>"><?php echo $this->translate('Projects') ?></a></li>
                        <?php } ?>
                    </ul>
                </div><!--/.nav-collapse -->

            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            
            <footer>
                <hr>
                <p>&copy; <?php echo date('Y') ?> by Freelancemins.com All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
