<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Freelance Minis!</span></h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi molestie vestibulum orci, ac consequat nisi ornare a. Sed ullamcorper nisl felis, non mollis eros sodales quis. </p>
    <p style="text-align:center; padding-top:10px;">
        <a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank">Customer  &raquo;</a>
        <a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank">Painter &raquo;</a>
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum </h3>
            </div>
            <div class="panel-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi molestie vestibulum orci, ac consequat nisi ornare a. Sed ullamcorper nisl felis, non mollis eros sodales quis. Etiam vel magna at nisl dictum pharetra ac at nisi. Mauris facilisis nisi quis tortor posuere tincidunt. Quisque quis tempus lacus, et tristique nisl. Nulla ante dolor, gravida id felis id, egestas venenatis felis. Pellentesque tortor libero, dapibus et euismod sit amet, dignissim at libero.</p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">Lorem ipsum  &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum </h3>
            </div>
            <div class="panel-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi molestie vestibulum orci, ac consequat nisi ornare a. Sed ullamcorper nisl felis, non mollis eros sodales quis. Etiam vel magna at nisl dictum pharetra ac at nisi. Mauris facilisis nisi quis tortor posuere tincidunt. Quisque quis tempus lacus, et tristique nisl. Nulla ante dolor, gravida id felis id, egestas venenatis felis. Pellentesque tortor libero, dapibus et euismod sit amet, dignissim at libero.</p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Lorem ipsum &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Lorem ipsum </h3>
            </div>
            <div class="panel-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi molestie vestibulum orci, ac consequat nisi ornare a. Sed ullamcorper nisl felis, non mollis eros sodales quis. Etiam vel magna at nisl dictum pharetra ac at nisi. Mauris facilisis nisi quis tortor posuere tincidunt. Quisque quis tempus lacus, et tristique nisl. Nulla ante dolor, gravida id felis id, egestas venenatis felis. Pellentesque tortor libero, dapibus et euismod sit amet, dignissim at libero.</p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Lorem ipsum  &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
