<?php
// module/Proposal/view/proposal/proposal/add.phtml:

$title = 'Add new proposal';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('proposal', array('action' => 'add')));
$form->prepare();

/*echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();*/

//Alternate form display
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();